/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DrawRouteImport } from './routes/draw'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SurveysIndexRouteImport } from './routes/surveys.index'
import { Route as FFormIdRouteImport } from './routes/f.$formId'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as SurveysSurveyIdIndexRouteImport } from './routes/surveys.$surveyId.index'
import { Route as ApiChatDrawRouteImport } from './routes/api.chat.draw'
import { Route as SurveysSurveyIdFormIndexRouteImport } from './routes/surveys.$surveyId.form.index'
import { Route as SurveysSurveyIdFormFormIdIndexRouteImport } from './routes/surveys.$surveyId.form.$formId.index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawRoute = DrawRouteImport.update({
  id: '/draw',
  path: '/draw',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveysIndexRoute = SurveysIndexRouteImport.update({
  id: '/surveys/',
  path: '/surveys/',
  getParentRoute: () => rootRouteImport,
} as any)
const FFormIdRoute = FFormIdRouteImport.update({
  id: '/f/$formId',
  path: '/f/$formId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveysSurveyIdIndexRoute = SurveysSurveyIdIndexRouteImport.update({
  id: '/surveys/$surveyId/',
  path: '/surveys/$surveyId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatDrawRoute = ApiChatDrawRouteImport.update({
  id: '/draw',
  path: '/draw',
  getParentRoute: () => ApiChatRoute,
} as any)
const SurveysSurveyIdFormIndexRoute =
  SurveysSurveyIdFormIndexRouteImport.update({
    id: '/surveys/$surveyId/form/',
    path: '/surveys/$surveyId/form/',
    getParentRoute: () => rootRouteImport,
  } as any)
const SurveysSurveyIdFormFormIdIndexRoute =
  SurveysSurveyIdFormFormIdIndexRouteImport.update({
    id: '/surveys/$surveyId/form/$formId/',
    path: '/surveys/$surveyId/form/$formId/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/draw': typeof DrawRoute
  '/login': typeof LoginRoute
  '/api/chat': typeof ApiChatRouteWithChildren
  '/f/$formId': typeof FFormIdRoute
  '/surveys/': typeof SurveysIndexRoute
  '/api/chat/draw': typeof ApiChatDrawRoute
  '/surveys/$surveyId/': typeof SurveysSurveyIdIndexRoute
  '/surveys/$surveyId/form/': typeof SurveysSurveyIdFormIndexRoute
  '/surveys/$surveyId/form/$formId/': typeof SurveysSurveyIdFormFormIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/draw': typeof DrawRoute
  '/login': typeof LoginRoute
  '/api/chat': typeof ApiChatRouteWithChildren
  '/f/$formId': typeof FFormIdRoute
  '/surveys': typeof SurveysIndexRoute
  '/api/chat/draw': typeof ApiChatDrawRoute
  '/surveys/$surveyId': typeof SurveysSurveyIdIndexRoute
  '/surveys/$surveyId/form': typeof SurveysSurveyIdFormIndexRoute
  '/surveys/$surveyId/form/$formId': typeof SurveysSurveyIdFormFormIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/draw': typeof DrawRoute
  '/login': typeof LoginRoute
  '/api/chat': typeof ApiChatRouteWithChildren
  '/f/$formId': typeof FFormIdRoute
  '/surveys/': typeof SurveysIndexRoute
  '/api/chat/draw': typeof ApiChatDrawRoute
  '/surveys/$surveyId/': typeof SurveysSurveyIdIndexRoute
  '/surveys/$surveyId/form/': typeof SurveysSurveyIdFormIndexRoute
  '/surveys/$surveyId/form/$formId/': typeof SurveysSurveyIdFormFormIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/draw'
    | '/login'
    | '/api/chat'
    | '/f/$formId'
    | '/surveys/'
    | '/api/chat/draw'
    | '/surveys/$surveyId/'
    | '/surveys/$surveyId/form/'
    | '/surveys/$surveyId/form/$formId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/draw'
    | '/login'
    | '/api/chat'
    | '/f/$formId'
    | '/surveys'
    | '/api/chat/draw'
    | '/surveys/$surveyId'
    | '/surveys/$surveyId/form'
    | '/surveys/$surveyId/form/$formId'
  id:
    | '__root__'
    | '/'
    | '/draw'
    | '/login'
    | '/api/chat'
    | '/f/$formId'
    | '/surveys/'
    | '/api/chat/draw'
    | '/surveys/$surveyId/'
    | '/surveys/$surveyId/form/'
    | '/surveys/$surveyId/form/$formId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DrawRoute: typeof DrawRoute
  LoginRoute: typeof LoginRoute
  ApiChatRoute: typeof ApiChatRouteWithChildren
  FFormIdRoute: typeof FFormIdRoute
  SurveysIndexRoute: typeof SurveysIndexRoute
  SurveysSurveyIdIndexRoute: typeof SurveysSurveyIdIndexRoute
  SurveysSurveyIdFormIndexRoute: typeof SurveysSurveyIdFormIndexRoute
  SurveysSurveyIdFormFormIdIndexRoute: typeof SurveysSurveyIdFormFormIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draw': {
      id: '/draw'
      path: '/draw'
      fullPath: '/draw'
      preLoaderRoute: typeof DrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surveys/': {
      id: '/surveys/'
      path: '/surveys'
      fullPath: '/surveys/'
      preLoaderRoute: typeof SurveysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/$formId': {
      id: '/f/$formId'
      path: '/f/$formId'
      fullPath: '/f/$formId'
      preLoaderRoute: typeof FFormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surveys/$surveyId/': {
      id: '/surveys/$surveyId/'
      path: '/surveys/$surveyId'
      fullPath: '/surveys/$surveyId/'
      preLoaderRoute: typeof SurveysSurveyIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/draw': {
      id: '/api/chat/draw'
      path: '/draw'
      fullPath: '/api/chat/draw'
      preLoaderRoute: typeof ApiChatDrawRouteImport
      parentRoute: typeof ApiChatRoute
    }
    '/surveys/$surveyId/form/': {
      id: '/surveys/$surveyId/form/'
      path: '/surveys/$surveyId/form'
      fullPath: '/surveys/$surveyId/form/'
      preLoaderRoute: typeof SurveysSurveyIdFormIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surveys/$surveyId/form/$formId/': {
      id: '/surveys/$surveyId/form/$formId/'
      path: '/surveys/$surveyId/form/$formId'
      fullPath: '/surveys/$surveyId/form/$formId/'
      preLoaderRoute: typeof SurveysSurveyIdFormFormIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiChatRouteChildren {
  ApiChatDrawRoute: typeof ApiChatDrawRoute
}

const ApiChatRouteChildren: ApiChatRouteChildren = {
  ApiChatDrawRoute: ApiChatDrawRoute,
}

const ApiChatRouteWithChildren =
  ApiChatRoute._addFileChildren(ApiChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DrawRoute: DrawRoute,
  LoginRoute: LoginRoute,
  ApiChatRoute: ApiChatRouteWithChildren,
  FFormIdRoute: FFormIdRoute,
  SurveysIndexRoute: SurveysIndexRoute,
  SurveysSurveyIdIndexRoute: SurveysSurveyIdIndexRoute,
  SurveysSurveyIdFormIndexRoute: SurveysSurveyIdFormIndexRoute,
  SurveysSurveyIdFormFormIdIndexRoute: SurveysSurveyIdFormFormIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
