/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as FFormIdIndexRouteImport } from './routes/f/$formId/index'
import { Route as ProtectedSurveysIndexRouteImport } from './routes/_protected/surveys/index'
import { Route as ProtectedDrawIndexRouteImport } from './routes/_protected/draw/index'
import { Route as ProtectedSurveysSurveyIdIndexRouteImport } from './routes/_protected/surveys/$surveyId/index'
import { Route as ProtectedSurveysSurveyIdFormIndexRouteImport } from './routes/_protected/surveys/$surveyId/form/index'
import { Route as ProtectedSurveysSurveyIdFormFormIdIndexRouteImport } from './routes/_protected/surveys/$surveyId/form/$formId/index'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const FFormIdIndexRoute = FFormIdIndexRouteImport.update({
  id: '/f/$formId/',
  path: '/f/$formId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedSurveysIndexRoute = ProtectedSurveysIndexRouteImport.update({
  id: '/surveys/',
  path: '/surveys/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDrawIndexRoute = ProtectedDrawIndexRouteImport.update({
  id: '/draw/',
  path: '/draw/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSurveysSurveyIdIndexRoute =
  ProtectedSurveysSurveyIdIndexRouteImport.update({
    id: '/surveys/$surveyId/',
    path: '/surveys/$surveyId/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSurveysSurveyIdFormIndexRoute =
  ProtectedSurveysSurveyIdFormIndexRouteImport.update({
    id: '/surveys/$surveyId/form/',
    path: '/surveys/$surveyId/form/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSurveysSurveyIdFormFormIdIndexRoute =
  ProtectedSurveysSurveyIdFormFormIdIndexRouteImport.update({
    id: '/surveys/$surveyId/form/$formId/',
    path: '/surveys/$surveyId/form/$formId/',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/api/chat': typeof ApiChatRoute
  '/login/': typeof LoginIndexRoute
  '/draw/': typeof ProtectedDrawIndexRoute
  '/surveys/': typeof ProtectedSurveysIndexRoute
  '/f/$formId/': typeof FFormIdIndexRoute
  '/surveys/$surveyId/': typeof ProtectedSurveysSurveyIdIndexRoute
  '/surveys/$surveyId/form/': typeof ProtectedSurveysSurveyIdFormIndexRoute
  '/surveys/$surveyId/form/$formId/': typeof ProtectedSurveysSurveyIdFormFormIdIndexRoute
}
export interface FileRoutesByTo {
  '/api/chat': typeof ApiChatRoute
  '/': typeof ProtectedIndexRoute
  '/login': typeof LoginIndexRoute
  '/draw': typeof ProtectedDrawIndexRoute
  '/surveys': typeof ProtectedSurveysIndexRoute
  '/f/$formId': typeof FFormIdIndexRoute
  '/surveys/$surveyId': typeof ProtectedSurveysSurveyIdIndexRoute
  '/surveys/$surveyId/form': typeof ProtectedSurveysSurveyIdFormIndexRoute
  '/surveys/$surveyId/form/$formId': typeof ProtectedSurveysSurveyIdFormFormIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/login/': typeof LoginIndexRoute
  '/_protected/draw/': typeof ProtectedDrawIndexRoute
  '/_protected/surveys/': typeof ProtectedSurveysIndexRoute
  '/f/$formId/': typeof FFormIdIndexRoute
  '/_protected/surveys/$surveyId/': typeof ProtectedSurveysSurveyIdIndexRoute
  '/_protected/surveys/$surveyId/form/': typeof ProtectedSurveysSurveyIdFormIndexRoute
  '/_protected/surveys/$surveyId/form/$formId/': typeof ProtectedSurveysSurveyIdFormFormIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/chat'
    | '/login/'
    | '/draw/'
    | '/surveys/'
    | '/f/$formId/'
    | '/surveys/$surveyId/'
    | '/surveys/$surveyId/form/'
    | '/surveys/$surveyId/form/$formId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/api/chat'
    | '/'
    | '/login'
    | '/draw'
    | '/surveys'
    | '/f/$formId'
    | '/surveys/$surveyId'
    | '/surveys/$surveyId/form'
    | '/surveys/$surveyId/form/$formId'
  id:
    | '__root__'
    | '/_protected'
    | '/api/chat'
    | '/_protected/'
    | '/login/'
    | '/_protected/draw/'
    | '/_protected/surveys/'
    | '/f/$formId/'
    | '/_protected/surveys/$surveyId/'
    | '/_protected/surveys/$surveyId/form/'
    | '/_protected/surveys/$surveyId/form/$formId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  LoginIndexRoute: typeof LoginIndexRoute
  FFormIdIndexRoute: typeof FFormIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/$formId/': {
      id: '/f/$formId/'
      path: '/f/$formId'
      fullPath: '/f/$formId/'
      preLoaderRoute: typeof FFormIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/surveys/': {
      id: '/_protected/surveys/'
      path: '/surveys'
      fullPath: '/surveys/'
      preLoaderRoute: typeof ProtectedSurveysIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/draw/': {
      id: '/_protected/draw/'
      path: '/draw'
      fullPath: '/draw/'
      preLoaderRoute: typeof ProtectedDrawIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/surveys/$surveyId/': {
      id: '/_protected/surveys/$surveyId/'
      path: '/surveys/$surveyId'
      fullPath: '/surveys/$surveyId/'
      preLoaderRoute: typeof ProtectedSurveysSurveyIdIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/surveys/$surveyId/form/': {
      id: '/_protected/surveys/$surveyId/form/'
      path: '/surveys/$surveyId/form'
      fullPath: '/surveys/$surveyId/form/'
      preLoaderRoute: typeof ProtectedSurveysSurveyIdFormIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/surveys/$surveyId/form/$formId/': {
      id: '/_protected/surveys/$surveyId/form/$formId/'
      path: '/surveys/$surveyId/form/$formId'
      fullPath: '/surveys/$surveyId/form/$formId/'
      preLoaderRoute: typeof ProtectedSurveysSurveyIdFormFormIdIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedDrawIndexRoute: typeof ProtectedDrawIndexRoute
  ProtectedSurveysIndexRoute: typeof ProtectedSurveysIndexRoute
  ProtectedSurveysSurveyIdIndexRoute: typeof ProtectedSurveysSurveyIdIndexRoute
  ProtectedSurveysSurveyIdFormIndexRoute: typeof ProtectedSurveysSurveyIdFormIndexRoute
  ProtectedSurveysSurveyIdFormFormIdIndexRoute: typeof ProtectedSurveysSurveyIdFormFormIdIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedDrawIndexRoute: ProtectedDrawIndexRoute,
  ProtectedSurveysIndexRoute: ProtectedSurveysIndexRoute,
  ProtectedSurveysSurveyIdIndexRoute: ProtectedSurveysSurveyIdIndexRoute,
  ProtectedSurveysSurveyIdFormIndexRoute:
    ProtectedSurveysSurveyIdFormIndexRoute,
  ProtectedSurveysSurveyIdFormFormIdIndexRoute:
    ProtectedSurveysSurveyIdFormFormIdIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  LoginIndexRoute: LoginIndexRoute,
  FFormIdIndexRoute: FFormIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
